SELECT sys_context('USERENV', 'CON_NAME') FROM dual;
select * from dba_pdbs;
select * from USER_TABLES;

CREATE TABLESPACE DB_TBS DATAFILE 'DB_TBS.dbf' SIZE 4M AUTOEXTEND ON;

CREATE TABLE ROLES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME NVARCHAR2(50) UNIQUE NOT NULL
) TABLESPACE DB_TBS;

CREATE TABLE STAFF (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME NVARCHAR2(50) UNIQUE NOT NULL,
    PRINCIPAL INT,
    ROLE INT NOT NULL,
    CONSTRAINT FK_STAFF_PRINCIPAL FOREIGN KEY (PRINCIPAL) REFERENCES STAFF(ID),
    CONSTRAINT FK_STAFF_ROLE FOREIGN KEY (ROLE) REFERENCES ROLES(ID)
) TABLESPACE DB_TBS;

CREATE TABLE TEST_DATA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GEO_DATA SDO_GEOMETRY,
    JSON_DATA NVARCHAR2(1000)
) TABLESPACE DB_TBS;

CREATE TABLE COMMITS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVELOPER INT NOT NULL,
    COMMIT_DATE TIMESTAMP NOT NULL,
    CONSTRAINT FK_COMMITS_DEVELOPER FOREIGN KEY (DEVELOPER) REFERENCES STAFF(ID)
) TABLESPACE DB_TBS;

CREATE TABLE TESTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TESTER INT NOT NULL,
    COMMIT INT NOT NULL,
    DATA_ID INT NOT NULL,
    PASSED CHAR(1) NOT NULL CHECK (PASSED IN ('Y', 'N')),
    CONSTRAINT FK_TESTS_TESTER FOREIGN KEY (TESTER) REFERENCES STAFF(ID),
    CONSTRAINT FK_TESTS_COMMIT FOREIGN KEY (COMMIT) REFERENCES COMMITS(ID),
    CONSTRAINT FK_TESTS_DATA FOREIGN KEY (DATA_ID) REFERENCES TEST_DATA(ID)
) TABLESPACE DB_TBS;

commit;