select DB_NAME();
create database SEPDB;
use SEPDB;

CREATE TABLE ROLES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(50) UNIQUE NOT NULL
);
go

CREATE TABLE STAFF (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(50) UNIQUE NOT NULL,
    PRINCIPAL INT,
    ROLE INT NOT NULL,
    CONSTRAINT FK_STAFF_PRINCIPAL FOREIGN KEY (PRINCIPAL) REFERENCES STAFF(ID),
    CONSTRAINT FK_STAFF_ROLE FOREIGN KEY (ROLE) REFERENCES ROLES(ID)
);
go

CREATE TABLE TEST_DATA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    GEO_DATA GEOMETRY,
    JSON_DATA NVARCHAR(1000)
);
go

CREATE TABLE COMMITS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DEVELOPER INT NOT NULL,
    COMMIT_DATE DATETIME NOT NULL,
    CONSTRAINT FK_COMMITS_DEVELOPER FOREIGN KEY (DEVELOPER) REFERENCES STAFF(ID)
);
go

CREATE TABLE TESTS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TESTER INT NOT NULL,
    COMMIT_ID INT NOT NULL,
    DATA_ID INT NOT NULL,
    PASSED CHAR(1) NOT NULL CHECK (PASSED IN ('Y', 'N')),
    CONSTRAINT FK_TESTS_TESTER FOREIGN KEY (TESTER) REFERENCES STAFF(ID),
    CONSTRAINT FK_TESTS_COMMIT FOREIGN KEY (COMMIT_ID) REFERENCES COMMITS(ID),
    CONSTRAINT FK_TESTS_DATA FOREIGN KEY (DATA_ID) REFERENCES TEST_DATA(ID)
);